color0 #0c0e14
color1 #e64572
color2 #89d36a
color3 #d7a23a
color4 #4f8fff
color5 #9d6dff
color6 #43c9ff
color7 #b7c4f2
color8 #2b314a
color9 #e64572
color10 #89d36a
color11 #d7a23a
color12 #4f8fff
color13 #9d6dff
color14 #43c9ff
color15 #d8e0ff
background #2a1922
selection_foreground #2a1b21
cursor #efdce8
cursor_text_color #2a1b21
foreground #f3c7d7
selection_background #f3c7d7
active_border_color #f2c1d4
inactive_border_color #ffd6e2
