#!/bin/bash

cat << 'EOF'
----
  ____  _        _ _        ____         _    __ _ _ 
 |  _ \(_) __ _(_| )___   |  _ \   ___ | |_ / _(_) | ___ 
 | | | | |/ _` | |// __|  | | | | / _ \| __| |_| | |/ _ \
 | |_| | | (_| | | \__ \  | |_| | (_) | |_|  _| | |  __/
 |____/|_|\__, |_| |___/  |____/ \___/ \__|_| |_|_|\___|
         |___/                                          
  ___            _         _ _            _ 
 |_ _|_ __   ___| |_ __ _| | | ___ _ __| |
  | || '_ \ / __| __/ _` | | |/ _ \ '__| |
  | || | | \__ \ || (_| | | |  __/ |  |_|
 |___|_| |_|___/\__\__,_|_|_|\___|_|  (_)

----
EOF

# Install Paru
if command -v paru >/dev/null 2>&1
then
    echo Paru installed, skipping...
else
    echo installing Paru...
    sudo pacman -S --needed base-devel git > /dev/null 2>&1
    git clone https://aur.archlinux.org/paru.git > /dev/null 2>&1
    cd paru > /dev/null 2>&1
    makepkg -si > /dev/null 2>&1
    cd ..  > /dev/null 2>&1
    rm -rf paru/  > /dev/null 2>&1
    echo Paru installed!

fi

echo Updating System...
paru -Syu --noconfirm > /dev/null 2>&1
echo System Updated!

install_program() {
    echo installing $1...
    paru -S --noconfirm --needed ${@:2} > /dev/null 2>&1
    echo $1 installed!
}

# Arg 1 = Text 
# Arg 2 = program to install

install_program Hyprland hyprland
install_program Thunar thunar
install_program Grim grim
install_program Slurp slurp
install_program Udiskie udiskie
install_program "WL Clipboard" wl-clipboard
install_program Ghostty ghostty
install_program Kitty kitty
install_program Zoxide zoxide
install_program QuickShell quickshell noctalia-shell
install_program NeoVim neovim luarocks tree-sitter-cli npm
install_program Zsh zsh starship
install_program Tmux tmux
install_program FastFetch fastfetch
install_program PipeWire pipewire
install_program SDDM sddm
install_program Btop btop
install_program Wine wine winetricks
install_program NetworkManager networkmanager
install_program Bluetooth bluez bluez-utils
install_program "Bibata Cursors" bibata-cursor-theme
install_program  Gtk3 gtk3
install_program  Qt5 qt5
install_program  Qt6 qt6
install_program  HyprQt6Engine hyprqt6engine

install_program Noto-Fonts noto-fonts
install_program Noto-Fonts-cjk noto-fonts-cjk
install_program Noto-Fonts-Emoji noto-fonts-emoji
install_program "Nerd Font Symbols" ttf-nerd-fonts-symbols ttf-nerd-fonts-symbols-common
install_program "Jet Brains Mono Nerd Font" ttf-jetbrains-mono-nerd
install_program "Caskaydia Cove Nerd Font" ttf-cascadia-code-nerd
install_program "OTF IPA Font" otf-ipafont
install_program "Adwaita Font" adwaita-fonts



sudo systemctl enable NetworkManager.service
sudo systemctl enable bluetooth.service


if [ -d /usr/share/sddm/themes/Makima-SDDM/ ]; then
    echo SDDM theme installed, skipping...
else
    echo Installling SDDM theme...
    
    if [ -f /etc/sddm.conf ];
    then
        echo Backing Up Old sddm.conf...
        sudo cp /etc/sddm.conf /etc/sddmbackup.conf
        sudo rm /etc/sddm.conf
    fi

    sudo touch /etc/sddm.conf
    sudo tee /etc/sddm.conf << EOF
[Theme]
    Current=Makima-SDDM
EOF
    sudo git clone https://github.com/Arnau029/Makima-SDDM.git
	sudo mv Makima-SDDM /usr/share/sddm/themes
    echo SDDM theme installed!
fi

if command -v cpg >/dev/null 2>&1
then
    echo Advanced Copy installed, skipping...
else
    echo installing Advanced Copy...
    cd
    curl https://raw.githubusercontent.com/jarun/advcpmv/master/install.sh --create-dirs -o ./advcpmv/install.sh && (cd advcpmv && sh install.sh)
    sudo mv ./advcpmv/advcp /usr/local/bin/cpg
    sudo mv ./advcpmv/advmv /usr/local/bin/mvg
    echo Advanced Copy installed!
fi   

cat << 'EOF'

----
  ___            _         _ _        _    _ 
 |_ _|_ __   ___| |_ __ _| | | __ _| |_(_) ___  _ __ 
  | || '_ \ / __| __/ _` | | |/ _` | __| |/ _ \| '_ \
  | || | | \__ \ || (_| | | | (_| | |_| | (_) | | | |
 |___|_| |_|___/\__\__,_|_|_|\__,_|\__|_|\___/|_| |_|

  _____ _        _      _               _ _ 
 |  ___(_)_ __ (_)___| |__    ___  __| | |
 | |_   | | '_ \| / __| '_ \ / _ \/ _` | |
 |  _|  | | | | | \__ \ | | |  __/ (_| |_|
 |_|    |_|_| |_|_|___/_| |_|\___|\__,_(_)

----
EOF
