# Dwindle

general {
    layout = dwindle
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}


# Variables

$mainMod = SUPER 
$terminal = ghostty
$fileManager = nautilus
$menu = qs -c noctalia-shell ipc call launcher toggle

# Binds

bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, B, togglesplit, # dwindle
