# Master

general {
    # layout = master
}

master {
    new_status = master
}

# Variables

$mainMod = SUPER 
$terminal = ghostty
$fileManager = nautilus
$menu = qs -c noctalia-shell ipc call launcher toggle

# Binds
